language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
node_js:
  - "10.15.1"
install: 
  - yarn install
before_script:
  - npm install -g git://github.com/ipfs/npm-go-ipfs#32acf52
jobs:
  include:
    - stage: 'Tests'
      name: 'Unit Tests'
      script: yarn test
    - script: yarn test:integration
      name: 'Integration Test'
