// WARNING: this file is autogenerated. Make local changes in ../jest.config.js
// instead!

module.exports = require('../jest.config.js')
module.exports.extends = "@rushstack/heft-node-rig/profiles/default/config/jest.config.json"

